import {
  AlertOutlined,
  ApiOutlined,
  AuditOutlined,
  BellOutlined,
  BlockOutlined,
  BuildOutlined,
  CloudServerOutlined,
  CodeOutlined,
  ConsoleSqlOutlined,
  ControlOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DisconnectOutlined,
  ForkOutlined,
  HddOutlined,
  IdcardOutlined,
  InsuranceOutlined,
  IssuesCloseOutlined,
  LinkOutlined,
  LoginOutlined,
  MonitorOutlined,
  ProductOutlined,
  SafetyCertificateOutlined,
  SettingOutlined,
  SolutionOutlined,
  TeamOutlined,
  UserOutlined,
  UserSwitchOutlined
} from "@ant-design/icons";

export const routers = [
    {
        key: 'dashboard',
        i18nKey:'menu.dashboard',
        label: '控制面板',
        icon: <DashboardOutlined/>,
    },
    {
        key: 'resource',
        i18nKey: 'menu.resource',
        label: '资源管理',
        icon: <CloudServerOutlined />,
        children: [
          {
            key: 'dbm-asset',
            i18nKey: 'menu.resource.dbm-asset',
            label: 'DB资产',
            icon: <DatabaseOutlined />,
          },
          {
            key: 'credential',
            i18nKey: 'menu.resource.credential',
            label: '授权凭证',
            icon: <IdcardOutlined />,
          },
          {
            key: 'access-gateway',
            i18nKey: 'menu.resource.access-gateway',
            label: '接入网关',
            icon: <ApiOutlined />,
          },
          {
            key: 'command',
            i18nKey: 'menu.resource.dynamic-command',
            label: '动态指令',
            icon: <CodeOutlined />,
          },
          {
            key: 'sqls',
            i18nKey: 'menu.resource.sql-scripts',
            label: '脚本管理',
            icon: <ConsoleSqlOutlined />,
          },
        ],
      },
      {
        key: 'git-manager',
        i18nKey: 'menu.git-manager',
        label: '版本管理',
        icon: <ForkOutlined />,
        children: [
          {
            key: 'git',
            i18nKey: 'menu.git-manager.version-control',
            label: '版本管理',
            icon: <ForkOutlined />,
          },
        ],
      },
      {
        key: 'build-manager',
        i18nKey: 'menu.build-manager',
        label: '构建管理',
        icon: <BuildOutlined />,
        children: [
          {
            key: 'build',
            i18nKey: 'menu.build-manager.build-management',
            label: '构建管理',
            icon: <BuildOutlined />,
          },
        ],
      },
      {
        key: 'session-audit',
        i18nKey: 'menu.session-audit',
        label: '会话审计',
        icon: <AuditOutlined />,
        children: [
          {
            key: 'online-session',
            i18nKey: 'menu.session-audit.online',
            label: '在线会话',
            icon: <LinkOutlined />,
          },
          {
            key: 'offline-session',
            i18nKey: 'menu.session-audit.history',
            label: '历史会话',
            icon: <DisconnectOutlined />,
          },
        ],
      },
      {
        key: 'log-audit',
        i18nKey: 'menu.log-audit',
        label: '日志审计',
        icon: <AuditOutlined />,
        children: [
          {
            key: 'login-log',
            i18nKey: 'menu.log-audit.login',
            label: '登录日志',
            icon: <LoginOutlined />,
          },
          {
            key: 'sql-log',
            i18nKey: 'menu.log-audit.sql-execution',
            label: '执行日志',
            icon: <ConsoleSqlOutlined />,
          },
          {
            key: 'webhook-push-log',
            i18nKey: 'menu.log-audit.webhook',
            label: '通知日志',
            icon: <AlertOutlined />,
          },
          {
            key: 'oper-log',
            i18nKey: 'menu.log-audit.operation',
            label: '操作日志',
            icon: <IssuesCloseOutlined />,
          },
        ],
      },
      {
        key: 'ops',
        i18nKey: 'menu.system-ops',
        label: '系统运维',
        icon: <ControlOutlined />,
        children: [
          {
            key: 'sensitive-command',
            i18nKey: 'menu.system-ops.sensitive-command',
            label: '敏感指令',
            icon: <CodeOutlined />,
          },
          {
            key: 'trigger-command',
            i18nKey: 'menu.system-ops.trigger-command',
            label: '触发指令',
            icon: <CodeOutlined />,
          },
          {
            key: 'webhook',
            i18nKey: 'menu.system-ops.webhook',
            label: '通知推送',
            icon: <BellOutlined />,
          },
          {
            key: 'job',
            i18nKey: 'menu.system-ops.scheduled-jobs',
            label: '计划任务',
            icon: <BlockOutlined />,
          },
          {
            key: 'storage',
            i18nKey: 'menu.system-ops.disk-storage',
            label: '磁盘空间',
            icon: <HddOutlined />,
          },
          {
            key: 'monitoring',
            i18nKey: 'menu.system-ops.monitoring',
            label: '系统监控',
            icon: <MonitorOutlined />,
          },
        ],
      },
      {
        key: 'security',
        i18nKey: 'menu.security-policy',
        label: '安全策略',
        icon: <SafetyCertificateOutlined />,
        children: [
          {
            key: 'sensitive-command-group',
            i18nKey: 'menu.security-policy.sensitive-strategy',
            label: '敏感策略',
            icon: <ProductOutlined />,
          },
          {
            key: 'trigger-command-group',
            i18nKey: 'menu.security-policy.trigger-strategy',
            label: '触发策略',
            icon: <ProductOutlined />,
          },
          {
            key: 'strategy',
            i18nKey: 'menu.security-policy.authorization',
            label: '授权策略',
            icon: <InsuranceOutlined />,
          },
          {
            key: 'access-security',
            i18nKey: 'menu.security-policy.access-control',
            label: '访问安全',
            icon: <SafetyCertificateOutlined />,
          },
          {
            key: 'login-policy',
            i18nKey: 'menu.security-policy.login-policy',
            label: '登录策略',
            icon: <LoginOutlined />,
          },
        ],
    },
    {
        key: 'identity',
        i18nKey: 'menu.identity-management',
        label: '用户管理',
        icon: <UserSwitchOutlined />,
        children: [
          {
            key: 'user',
            i18nKey: 'menu.identity-management.users',
            label: '用户管理',
            icon: <UserOutlined />,
          },
          {
            key: 'role',
            i18nKey: 'menu.identity-management.roles',
            label: '角色管理',
            icon: <SolutionOutlined />,
          },
          {
            key: 'user-group',
            i18nKey: 'menu.identity-management.user-groups',
            label: '用户组管理',
            icon: <TeamOutlined />,
          },
        ],
    },
    // {
    //     key: 'authorised',
    //     label: '授权策略',
    //     icon: <UserSwitchOutlined/>,
    //     children: [
    //         {
    //             key: 'strategy',
    //             label: '授权策略',
    //             icon: <InsuranceOutlined/>,
    //         },
    //     ]
    // },
    {
        key: 'setting',
        i18nKey: 'menu.system-settings',
        label: '系统设置',
        icon: <SettingOutlined/>,
    },
    {
        key: 'info',
        label: '个人中心',
        i18nKey: 'menu.user-center',
        icon: <UserOutlined />,
    },
]